before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
brew:
  github:
    owner: yi-jiayu
    name: homebrew-tap
  homepage: "https://github.com/yi-jiayu/git-get"
  description: "Clone git repositories into namespaced directories like go get."
changelog:
  filters:
    exclude:
      - ^ci
      - ^goreleaser
