before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
brew:
  github:
    owner: yi-jiayu
    name: homebrew-tap
  homepage: "https://github.com/yi-jiayu/git-get"
  description: "Clone git repositories into namespaced directories like go get."
