version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go test -v -coverprofile=coverage.txt -covermode=count ./...
      - run: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: circleci/golang:1.11
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - approve-release:
          type: approval
          requires:
            - test
      - release:
          requires:
            - approve-release
